language: java
jdk:
  - oraclejdk8
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git checkout master
  - git add runnable/freak-island.jar
  - git commit -m "teste auto update jar"
  - git push "https://${GH_TOKEN}@github.com/gabrielcedran/coding-puzzle.git" master
  - git status
env:
  global:
    secure: iE/qvkTjvG5nVjluP2fc5BuAQM5lBcOU9B0F3Y4Z8En8l+pZIHba7Bv8+twJUfS+Z+A8FV4vwLUEDm1AUpeFzOOXk3o7BPGv80x/imadk5RqZLUijgups91k8iTdyuaJljwMSiBBAMenTrMkHfkADVyecQ76fmKY4AwQYkgjGzwWmD+pXi7+ceuyzGYajXUKfSSQkusdne2hVQDVQPD5RwjW757dZuAwgO56bf8HfflU4zG4R+zVahre1hi0Rr/ln+4rvzn23DQxG2gNAEFmAQk1s1gwJIxajeVNg9jboFIIdhcWym6la70onDGqVD3ecc2/A1PsxU08l8KWDgkKUIRT/h8IIUWGRf8sUWkEkufKS6VpDqZKmgDpAXGkKOjK96hY0BdMLPDGRinbaE2O8kFjNf1olOBQPxKOGhnE/y1yc1/3TUt0Uo+fXxKZn/OhieX/bBM6jeoXoFGVj29QvuHK0dk8UJV5Su7O2q2cT8dH/SGj4K8MHW86XrA0Vy46ulVJsUfNouHhLkhUXV2q/rmYcbn7XYdGq5W/kWcPs4K6rB8khZ/SBVtaZPFJGtug2ojkfitdabXz8qeQfwyJaAIwl8chMpe1HLfLjqeCUtJ9aWkqWqI6fKCg1xDpevAubnCRgW0q86dIBexzICq/6JTwvdMSgARkuWTMtAj0U7Q=
